# Generated by Django 3.2 on 2021-04-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('sub_heading', models.CharField(max_length=1000)),
            ],
        ),
    ]
